const accountSid = 'AC5bee201aacd665d437857f4803eb7f67';
const authToken = '003c95a0349d93d8a98cf1ada269c6ce';
const client = require('twilio')(accountSid, authToken);
const nodemailer = require('nodemailer');


const transport = nodemailer.createTransport({
    host: "smtp.mailtrap.io",
    port: 2525,
    auth: {
      user: "1a2b3c4d5e6f7g", //generated by Mailtrap
      pass: "1a2b3c4d5e6f7g" //generated by Mailtrap
    }
});


const mailOptions = {
    from: '"Example Team" <from@example.com>',
    to: 'user1@example.com, user2@example.com',
    subject: 'Nice Nodemailer test',
    text: 'Hey there, it’s our first message sent with Nodemailer ;) ',
    html: '<b>Hey there! </b><br> This is our first message sent with Nodemailer'
};

async function sendSMS(message, phoneNumber) {
    return client.messages
        .create({
            body: message,
            from: '+18329816323',
            to: phoneNumber
        });
}



module.exports = {
    sendSMS,
};